name: Build CSI on Windows

on:
  push:
    branches: [ main, cmake-test ]
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      - name: Configure CMake (MSVC)
        run: >
          cmake -B ${{ steps.strings.outputs.build-output-dir }}
          -DCMAKE_CXX_COMPILER=cl
          -DCMAKE_C_COMPILER=cl
          -DCMAKE_BUILD_TYPE=Release
          -S ${{ github.workspace }}

      - name: Build
        run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config Release

      - name: Debug Build Output
        run: dir /s *.dll
        shell: cmd

      - name: Package Release ZIP
        run: |
          mkdir Package\UserPlugins
          copy .\build\Release\ControlSurfaceIntegrator.dll Package\UserPlugins\
          xcopy Scripts Package\Scripts\ /E /I
          xcopy CSI Package\CSI\ /E /I
          cd Package
          7z a ..\CSI_Windows.zip *
        shell: cmd

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CSI_Windows
          path: CSI_Windows.zip