name: Build on macOS

on:
  push:
    branches:
      - main
      - cmake-test
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1

    - name: Configure with CMake preset
      run: cmake --preset=macos-x86_64

    - name: Build project
      run: cmake --build --preset=macos-x86_64Release