name: Build on Linux

on:
  push:
    branches: [ main, cmake-test ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install CMake (if not already available)
      run: sudo apt-get update && sudo apt-get install -y cmake

    - name: Configure CMake
      run: cmake --preset=linux64

    - name: Build
      run: cmake --build ${{ github.workspace }}/build --preset=linux64Release

    - name: Debug Build Output
      run: find . -name '*.so'

    - name: Package Release ZIP
      run: |
        mkdir -p Package/UserPlugins
        cp ./build/reaper_csurf_integrator.so Package/UserPlugins/
        cp -r Scripts Package/
        cp -r CSI Package/
        cd Package
        zip -r ../CSI_Linux.zip *
      shell: bash

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: CSI_Linux
        path: CSI_Linux.zip