name: Build on macOS

on:
  push:
    branches:
      - main
      - cmake-test
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: brew install make

    - name: Build with make
      run: |
        cd Mac
        make
