name: Build on Linux

on:
  push:
    branches:
      - main
      - cmake-test
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install CMake (if not already available)
      run: sudo apt-get update && sudo apt-get install -y cmake

    - name: Configure with CMake preset
      run: cmake --preset=linux64

    - name: Build project
      run: cmake --build --preset=linux64Release

    - name: Package Linux Release ZIP
      run: |
        mkdir -p Package/UserPlugins
        cp build/libreaper_csurf_integrator.so Package/UserPlugins/
        cp -r Scripts Package/
        cp -r CSI Package/
        cd Package
        zip -r ../CSI_Linux.zip *
      shell: bash

    - name: Upload Linux Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: CSI_Linux
        path: CSI_Linux.zip